Insert into BATCH (BATCH_ID, TRAINING_NAME, TRAINING_TYPE, SKILL_TYPE, LOCATION_ID, TRAINER, CO_TRAINER, START_DATE, END_DATE, GOOD_GRADE, PASSING_GRADE) values (1, 'TestingBatch1', 'Revature', 'Full Stack Java/JEE', 10, 'Patrick Walsh', 'Dan Pickles', '2018-10-05', '2018-11-05', 80, 70);

Insert into BATCH (BATCH_ID, TRAINING_NAME, TRAINING_TYPE, SKILL_TYPE, LOCATION_ID, TRAINER, START_DATE, END_DATE, GOOD_GRADE, PASSING_GRADE) values (2, 'TestingBatch2', 'Revature', 'PEGA BPM', 20, 'Dan Pickles', '2018-07-10', '2018-09-15', 70, 65);

Insert into BATCH (BATCH_ID, TRAINING_NAME, TRAINING_TYPE, SKILL_TYPE, LOCATION_ID, TRAINER, START_DATE, END_DATE, GOOD_GRADE, PASSING_GRADE) values (3, 'TestingBatch3', 'Corporate', 'Full Stack Java/JEE', 30, 'Ravi Singh', '2018-07-10', '2018-09-15', 85, 70);
